spring:
  application:
    name: file-management
  datasource:
    username: postgres
    password: 7777
    url: jdbc:postgresql://localhost:5432/file_management
  jpa:
    hibernate:
      ddl-auto: update
  main:
    allow-circular-references: true

jwt:
  secret: a7b49f2c628facf950bffe6f734ec3158c9eebc40d2c68089ca3505ce8cde38c
  lifetime: 24h

minio:
  url: https://play.min.io
  accessKey: Q3AM3UQ867SPQQA43P2F
  secretKey: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG