name: Run tests and build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 7777
          POSTGRES_DB: file_management
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        volumes:
          - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'amazon-corretto'
          java-version: '21'

      - name: Run tests
        run: mvn test

      - name: Build Docker images
        if: success()
        run: docker build -t file-management-back:latest .

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and push docker compose
        run: |
          docker-compose up --build -d
